# Generated by Django 4.2.19 on 2025-02-10 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milk_collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollectionentry',
            name='collection_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milkcollectionentry',
            name='collection_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='milkcollectionentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
