# Generated by Django 4.2.19 on 2025-03-04 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk_collection_app', '0002_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to='milk_collection_app.collectioncenter')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to='milk_collection_app.farmer')),
            ],
        ),
    ]
