# Generated by Django 4.2.19 on 2025-02-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_collection_app', '0003_customer_order_farmer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='customer',
        ),
    ]
