# Generated by Django 4.2.19 on 2025-02-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_collection_app', '0004_remove_farmer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Operator', 'Operator')], max_length=50),
        ),
    ]
